### ISSUE TITLE
Building for aarch64

### ISSUE THREAD

**Issue by eddybl** [epics-training/training-vm#10]
I am currently trying to use this setup to build this on an Apple Silicon Mac using [UTM](https://github.com/utmapp/UTM) instead of VirtualBox.

For this scenario I used Rocky-9.3-aarch64-boot.iso and I can probably write up a guide, once I made some further tests.

One issue I encountered is for installing the Java JDK, as the 64bit JDK is specified explicitly and I had to make the following change:

```diff
Index 78d6a47..7778bbf 100644
--- a/ansible/roles/epics-tools/tasks/install_java.yml
+++ b/ansible/roles/epics-tools/tasks/install_java.yml
@@ -19,7 +19,7 @@
 - name: install open jdk 17
   become: true
   ansible.builtin.unarchive:
-    src: https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.10%2B7/OpenJDK17U-jdk_x64_linux_hotspot_17.0.10_7.tar.gz
+    src: https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.10%2B7/OpenJDK17U-jdk_aarch64_linux_hotspot_17.0.10_7.tar.gz
```

There probably is a more elegant way of determine the current architecture? Because everything else (except building the Bluesky Docker container) seemed to work, at least in regards to building (but I havn't tried to run every example yet)

**Comment by eddybl** [comment]
Building the documentation for Phoebus is actually not working, because Sphinx-binary does not provide aarch64 binares ( https://github.com/trustin/sphinx-binary/issues/10 )

**Comment by eddybl** [comment]
> Building the documentation for Phoebus is actually not working, because Sphinx-binary does not provide aarch64 binares ( [trustin/sphinx-binary#10](https://github.com/trustin/sphinx-binary/issues/10) )

which again is required by sphinx-maven-plugin, which in itself does not seem to be maintained (last commit 3+ years)

**Comment by ralphlange** [comment]
So building the documentation should be suppressed for aarch64?

**Comment by eddybl** [comment]
yes, after commenting out the docs building task in ansible there were no more errors.

I was also able to build and run the epcis7 qsrv test ioc and was able to start phoebus itself.

Another issue is the $PATH definition, not sure where this happens:

```bash
echo $PATH
/opt/epics/base-7.0.8/bin/linux-x86_64:/opt/epics/seq-2.2.9/bin/linux-x86_64:/opt/epics/pvxs-1.3.1/bin/linux-x86_64:/home/epics-dev/.local/bin:/home/epics-dev/bin:/opt/epics/base-7.0.8/bin/linux-x86_64:/opt/epics/seq-2.2.9/bin/linux-x86_64:/opt/epics/pvxs-1.3.1/bin/linux-x86_64:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
```

this is all linking to the wrong `linux-` binary folder

**Comment by ralphlange** [comment]
That's at the end of build_module.yml (3rd tasks from the end).
Hard-coded so far.
The EPICS architecture needs to be added as a fact so it can be used at those places.

**Comment by eddybl** [comment]
For our Phoebus build we do not build the documentation explicitly as far as I can tell, but it is still present, but I haven't looked into the details as to how this happens

**Comment by eddybl** [comment]
Except the documentation building, this was implemented with https://github.com/epics-training/training-vm/pull/11
